# Generated by Django 4.2.7 on 2023-12-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_email_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='prev_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
