# Generated by Django 4.2.7 on 2023-12-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_emprestimo'),
        ('accounts', '0006_customuser_prev_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='livros',
            field=models.ManyToManyField(to='livros.livro'),
        ),
    ]
