# Generated by Django 4.2.7 on 2023-12-03 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_livros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='livros',
        ),
    ]
