# Generated by Django 4.2.7 on 2023-11-30 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='autores',
            new_name='autor',
        ),
    ]
