# Generated by Django 4.2.7 on 2023-12-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_livro_autor_alter_livro_genero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': [models.OrderBy(models.F('id'))]},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': [models.OrderBy(models.F('id'))]},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': [models.OrderBy(models.F('id'))]},
        ),
    ]
