# Generated by Django 4.2.7 on 2023-12-03 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livros', '0003_alter_autor_options_alter_genero_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='alunos',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
