# Generated by Django 4.2.7 on 2023-12-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_livro_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='alunos',
        ),
    ]
